### ISSUE TITLE
what does this assert means？

### ISSUE THREAD

**Issue by wsxk** [OSUSecLab/SymLM#10]
Traceback (most recent call last):
  File "training_evaluation\function_name_prediction.py", line 152, in <module>
    cli_main()
  File "training_evaluation\function_name_prediction.py", line 149, in cli_main
    main(args)
  File "training_evaluation\function_name_prediction.py", line 29, in main
    _main(args)
  File "training_evaluation\function_name_prediction.py", line 59, in _main
    model = FuncNamePred.from_pretrained(
  File "C:\Users\wsxk\Documents\SymLM\fairseq\models\roberta_mf\function_name_prediction.py", line 200, in from_pretrained
    x = hub_utils.from_pretrained(
  File "C:\Users\wsxk\Documents\SymLM\fairseq\hub_utils.py", line 71, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Users\wsxk\Documents\SymLM\fairseq\checkpoint_utils.py", line 243, in load_model_ensemble_and_task
    task = tasks.setup_task(args)
  File "C:\Users\wsxk\Documents\SymLM\fairseq\tasks\__init__.py", line 20, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "C:\Users\wsxk\Documents\SymLM\fairseq\tasks\masked_lm_mf.py", line 93, in setup_task
    assert len(paths) == len(params.fields) + 1  # one more for control flow
AssertionError

**Comment by wsxk** [comment]
It seems that the parameter `paths` don't used in fairseq\tasks\masked_lm_mf.py？

**Comment by xinjin95** [comment]
Hi @wsxk,

Can you provide more details about this error message? For example, what command did you run? Normally, this task script won't be invoked as it's not the task file for SymLM.

**Comment by wsxk** [comment]
I use `training_evaluation/prediction.sh`  to prediction function names for test binaries,as mentioned in `README.md`. And I donwload the `checkpoint_best.pt`.

**Comment by wsxk** [comment]
as I add print function,I found :
```
paths:
['caller1', 'caller2', 'external_callee1', 'external_callee2', 'internal_callee1', 'internal_callee2', 'self']
params.fields:
['static', 'inst_pos_emb', 'op_pos_emb', 'arch_emb', 'byte1', 'byte2', 'byte3', 'byte4']
```

**Comment by xinjin95** [comment]
Hi @wsxk,

`checkpoint_best.pt` is the pertained model from Trex. it's not our function name prediction model, which is fine-tuned from this model. To train our model, you have to follow the training instructions. After training, you can use the `prediction.sh` to perform inference.

**Comment by wsxk** [comment]
thank you for your explicit explanation! By the way, to fine-tune this model,what is your gpu configuration?

**Comment by xinjin95** [comment]
We used NVIDIA GEFORCE GTX 1080 Ti. And we found single 1080Ti GPU can run our training. You can adjust some parameters in [training_evaluation/train.sh](https://github.com/OSUSecLab/SymLM/tree/main/training_evaluation/train.sh) to fit your need, e.g., `MAX_SENTENCES` and `TOTAL_EPOCHs`.
